// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// La CLI Prisma (migrate, studio…) se connecte via une URL unique : le jeton
// d'authentification Turso doit donc être intégré à l'URL pour ces commandes,
// alors que le client applicatif (src/lib/prisma.ts) les passe séparément.
const url = process.env["DATABASE_AUTH_TOKEN"]
  ? `${process.env["DATABASE_URL"]}?authToken=${process.env["DATABASE_AUTH_TOKEN"]}`
  : process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url,
  },
});
